modLoader = "kotlinforforge"
loaderVersion = "[5,)"
issueTrackerURL = "https://github.com/trainb0y/fabrizoom/issues"
license = "MIT"

[[mods]]
modId = "fabrizoom"
version = "$mod_version"
displayName = "FabriZoom"
authors = "trainb0y, EnnuiL"
description = "Lightweight, cross-platform, configurable zoom. Fork of OkZoomer v4"
logoFile = "assets/fabrizoom/icon.png"

[[mixins]]
config = "fabrizoom.mixins.json"

[[dependencies.fabrizoom]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fabrizoom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fabrizoom]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.5,)"
ordering = "NONE"
side = "CLIENT"